apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: drone-agent
  name: drone-agent
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: drone-agent
    spec:
      containers:
      - args:
        - agent
        env:
        - name: DRONE_SECRET
        - name: DRONE_SERVER
          value: 10.43.250.255:9000
        - name: DRONE_SECRET
          valueFrom:
            secretKeyRef:
              name: literal-token
              key: DRONE_SECRET
        image: drone/agent:0.8
        name: drone-agent
        resources: {}
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: drone-agent-claim0
      restartPolicy: Always
      volumes:
      - name: drone-agent-claim0
        persistentVolumeClaim:
          claimName: drone-agent-claim0
status: {}
